### ISSUE TITLE
DHL

### ISSUE THREAD

**Issue by monkeyisland1992** [ZeiP/harbour-paketti#30]

**Comment by monkeyisland1992** [comment]
thank you for the version. 
but i get the problem that the bulb for dhl turns not on green as by hermes. it seems still that the app cant disconnet from the dhl site?

**Comment by ZeiP** [comment]
Thanks for the report! For me the code you provided almost worked now, except there was a bit different information in the events. I released a fixed version 0.8.1 to Openrepos and here: https://github.com/ZeiP/harbour-paketti/releases/tag/v0.8.1  Can you try it out and see if it works now correctly? Thanks!

**Comment by monkeyisland1992** [comment]
See here : 
![Bildschirmfoto_20210103_003](https://user-images.githubusercontent.com/17298261/103483654-1893f300-4de9-11eb-8dbe-5f091920ba94.png)

**Comment by ZeiP** [comment]
Yep. The problem currently is that the DHL API has somewhat strict limits to how often the API can be called, and as I just an hour ago queried the same number multiple times the limit is currently full. That error at least should vanish with time, try again for example in the next hour. You can see the error message that comes from the API in the first paragraph, that's straight from the API.

**Comment by monkeyisland1992** [comment]
> 
> 
> Yep. The problem currently is that the DHL API has somewhat strict limits to how often the API can be called, and as I just an hour ago queried the same number multiple times the limit is currently full. That error at least should vanish with time, try again for example in the next hour. You can see the error message that comes from the API in the first paragraph, that's straight from the API.

It is working. Great thank you.

**Comment by ZeiP** [comment]
Great, thanks for getting back and confirming! If you encounter any further problems in the future, feel free to open an issue. Have a nice week!
