### ISSUE TITLE
Posti: Failed to parse JSON

### ISSUE THREAD

**Issue by Termitebug** [ZeiP/harbour-paketti#48]
Onko Posti muuttanut taas omaa järjestelmäänsä? Monta samaa mainintaa jo Jolla Storessa.
Has Posti changes again it's own system? There is a couple of same mentions at Jolla Store.

**Comment by ZeiP** [comment]
Näemmä näin on taas käynyt, jep. Koitan saada uutta versiota buildattua, mutta valitettavasti koneen vaihdon myötä Sailfishin SDK lakkasi myös toimimasta ja debuggaus on aika vaikeaa sen takia. Koitan saada ongelman selvitettyä piakkoin.

**Comment by Sepinm** [comment]
Rajapinta on näemmä karannut tänne: https://api.posti.fi/api-tracking.html

Olisiko ihan `https://api.posti.fi/api-tracking.html#/tracking/7/shipments/trackingnumber/ + code` En vielä ehtinyt itse testata buildailla, kun tässä täytyy lähteä elantoa ansaitsemaan.

**Comment by ZeiP** [comment]
Noniin, sain lopulta Sailfish IDE:n taas toimimaan pitkän säädön jälkeen. Tuo @Sepinm'n löytämä rajapinta vaatii ilmeisesti sopimuksen joten se ei vaikuta mahdolliselta. Postin sivuilla rajapinta on siirtynyt toiseen osoitteeseen, mutta nykyään autentikoimattomana saa enää paketin statuksen – tapahtumien saaminen näyttää vaativan ainakin OAuth-tuen implementoinnin. Tein nyt toistaiseksi korjauksen siten, että ainakin paketin status näytetään, tätä olisi toki hyvä laajentaa jos joku keksii miten.
