### ISSUE TITLE
Ei onnistu hakemaan lähetysten tietoja.

### ISSUE THREAD

**Issue by Ingvix** [ZeiP/harbour-paketti#9]
Liekö syypää tällä rivillä:
`[W] unknown:35 - file:///usr/share/harbour-paketti/qml/pages/plug_itella.js:35: TypeError: Cannot read property 'en' of null`
Sovelluksessa kaikki lähetykset näyttävät päivityspalkkia ajasta ikuisuuteen.

**Comment by ZeiP** [comment]
Postin rajapintaan oli ilmeisesti ilmestynyt seurantatapahtumia, joissa ei ollut lainkaan kuvausta. Julkaisin äsken Openreposissa (ja täällä Githubissa) ongelman korjaavan version 0.6.5.

**Comment by Ingvix** [comment]
Valittaa uudemmallakin versiolla samasta. Koitin poistaa ~/.local/share/harbour-paketti-hakemiston, jos vanhoilla tiedoilla olisi jotain vaikutusta asiaan, mutta eipä tainnut olla. Uudelleenasennusta myös yritin, jos päivityksessä meni jokin pieleen, mutta ei tapahtunut parannusta. Tässäpä yksi uhrattava lähetystunnus testiin, jos vaikka siinä on jotain mätää: SP105020340FI

**Comment by ZeiP** [comment]
Tuosta lähetystunnuksesta näemmä puuttui myös lähetystuotteen nimi, jonka käsittely ei myöskään ollut kovin virhesietoinen. Pitäisi kirjoittaa nuo sisäänlukukoodit uudelleen vikasietoisemmiksi.

**Comment by ZeiP** [comment]
Julkaisin OpenReposiin ja tänne Githubiin version 0.6.6, jossa ainakin tuo antamasi testitunnus toimii. Jolla-kauppaan en sitä saa suoraan itse lisättyä, katson ehkä vähän tuota sisäänlukukoodien uusimista ennenkuin lähetän seuraavan version Jolla-kaupan sovelluksen ylläpitäjälle.

**Comment by Ingvix** [comment]
Nyt toimii mallikkaasti. Kiitoksia vain.
